global:
  external_labels:
      monitor: 'Monitoring'

rule_files:
  - 'alerts.yml'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
    - job_name: traefik
      scrape_interval: 15s
      scrape_timeout: 5s
      metrics_path: /metrics
      scheme: http
      static_configs:
      - targets:
        - reverse-proxy:8082

    - job_name: cadvisor
      scrape_interval: 15s
      scrape_timeout: 2s
      metrics_path: /metrics
      scheme: http
      static_configs:
      - targets:
        - cadvisor:8080

    - job_name: node-exporter
      scrape_interval: 15s
      scrape_timeout: 2s
      metrics_path: /metrics
      scheme: http
      static_configs:
      - targets:
        - node-exporter:9100